deploy_as: on-site-docker-container

docker_image: "{{aws_docker_registry}}/{{service}}"

service_port: 8633

register_with_consul:
  - name: "{{ service }}"
    healthcheck_path: "/ping"
    port: "{{ service_port }}"

port_mappings:
- host_port: "{{service_port}}"
  container_port: 80

volumes:
- "/var/log/{{service}}:/var/log/nginx"

